obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.35
inflation_radius: 0.50
observation_sources: scan
scan: {sensor_frame: /kinect_depth_frame, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
